AWSTemplateFormatVersion: '2010-09-09'
Description: 'Database Stack'

Resources:
  EC2Instance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://s3.amazonaws.com/stelligent-sandbox-bucket/EC2.yml
      TimeoutInMinutes: '60'