---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance
Parameters:
  SubNetID:
    Type: String

Resources:
  DatabaseAccessInstance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-09208e69ff3feb1db
        SubnetId: !Ref SubNetID