---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack'

Parameters:
  VPCTemplateURL:
    Description: S3 URL to VPC Template
    Type: String

  EC2TemplateURL:
    Description: S3 URL to EC2 Template
    Type: String

Resources:
  DemoVPC:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref VPCTemplateURL
      TimeoutInMinutes: '60'

  DemoEC2:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref EC2TemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        SubNetID:
          Fn::GetAtt:
          - DemoVPC
          - Outputs.PublicSubnetId
